version: "3.8"
services:
  frontend:
    build:
      context: ..
      dockerfile: ./infrastructure/docker/gatsby/Dockerfile
    volumes:
      - ../frontend:/usr/src/app/frontend:cached
    ports:
      - 8000:8000
    depends_on:
      - backend
    init: true
  backend:
    build:
      context: ..
      dockerfile: ./infrastructure/docker/golang/Dockerfile
    volumes:
      - ../backend:/usr/src/app/backend:cached
    ports:
      - 8080:8080
    depends_on:
      - db
    init: true
  db:
    image: mysql:5.7.12
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - react-go-db:/var/lib/mysql:delegated
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/log:/var/log/mysql
    init: true
    tty: true
volumes:
  react-go-db:
